CREATE TABLE IF NOT EXISTS "POPULATION DATA"(
    "NAME" TEXT,
    "LSAD" TEXT,
    "ESTIMATESBASE2020" INTEGER,
    "POPESTIMATE2020" INTEGER,
    "POPESTIMATE2021" INTEGER,
    "POPESTIMATE2022" INTEGER,
    "NPOPCHG2020" INTEGER,
    "NPOPCHG2021" INTEGER,
    "NPOPCHG2022" INTEGER,
    PRIMARY KEY("NAME")
);

CREATE TABLE IF NOT EXISTS "GDP DATA" (
    "GEOFIPS" INTEGER,
    "GEONAME" TEXT,
    "2020" INTEGER,
    "2021" INTEGER,
    "2022" INTEGER,
    PRIMARY KEY("GEONAME")
